
import { Tool } from './types';
import {
  MergeIcon,
  SplitIcon,
  CompressIcon,
  WordIcon,
  PowerPointIcon,
  ExcelIcon,
  EditIcon,
  PdfToJpgIcon,
  JpgToPdfIcon,
  SignIcon,
  WatermarkIcon,
  RotateIcon,
  HtmlToPdfIcon,
  UnlockIcon,
  ProtectIcon,
  OrganizeIcon,
  PdfToPdfAIcon,
  RepairIcon,
  PageNumbersIcon,
  ScanToPdfIcon,
  OcrPdfIcon,
  ComparePdfIcon,
  RedactPdfIcon,
  CropPdfIcon,
} from './components/icons';

export const TOOLS: Tool[] = [
  {
    id: 'merge-pdf',
    title: 'Merge PDF',
    description: 'Combine PDFs in the order you want with the easiest PDF merger available.',
    Icon: MergeIcon,
    color: 'bg-orange-500',
    hoverColor: 'hover:bg-orange-600',
    textColor: 'text-orange-500',
    category: 'organize',
  },
  {
    id: 'split-pdf',
    title: 'Split PDF',
    description: 'Separate one page or a whole set for easy conversion into independent PDF files.',
    Icon: SplitIcon,
    color: 'bg-orange-500',
    hoverColor: 'hover:bg-orange-600',
    textColor: 'text-orange-500',
    category: 'organize',
  },
  {
    id: 'compress-pdf',
    title: 'Compress PDF',
    description: 'Reduce file size while optimizing for maximal PDF quality.',
    Icon: CompressIcon,
    color: 'bg-green-500',
    hoverColor: 'hover:bg-green-600',
    textColor: 'text-green-500',
    category: 'optimize',
  },
  {
    id: 'pdf-to-word',
    title: 'PDF to Word',
    description: 'Easily convert your PDF files into easy to edit DOC and DOCX documents.',
    Icon: WordIcon,
    color: 'bg-blue-500',
    hoverColor: 'hover:bg-blue-600',
    textColor: 'text-blue-500',
    category: 'convert-from',
  },
  {
    id: 'pdf-to-powerpoint',
    title: 'PDF to PowerPoint',
    description: 'Turn your PDF files into easy to edit PPT and PPTX slideshows.',
    Icon: PowerPointIcon,
    color: 'bg-red-500',
    hoverColor: 'hover:bg-red-600',
    textColor: 'text-red-500',
    category: 'convert-from',
  },
  {
    id: 'pdf-to-excel',
    title: 'PDF to Excel',
    description: 'Pull data straight from PDFs into Excel spreadsheets in a few short seconds.',
    Icon: ExcelIcon,
    color: 'bg-green-700',
    hoverColor: 'hover:bg-green-800',
    textColor: 'text-green-700',
    category: 'convert-from',
  },
  {
    id: 'word-to-pdf',
    title: 'Word to PDF',
    description: 'Make DOC and DOCX files easy to read by converting them to PDF.',
    Icon: WordIcon,
    color: 'bg-blue-500',
    hoverColor: 'hover:bg-blue-600',
    textColor: 'text-blue-500',
    category: 'convert-to',
  },
  {
    id: 'powerpoint-to-pdf',
    title: 'PowerPoint to PDF',
    description: 'Make PPT and PPTX slideshows easy to view by converting them to PDF.',
    Icon: PowerPointIcon,
    color: 'bg-red-500',
    hoverColor: 'hover:bg-red-600',
    textColor: 'text-red-500',
    category: 'convert-to',
  },
  {
    id: 'excel-to-pdf',
    title: 'Excel to PDF',
    description: 'Make EXCEL spreadsheets easy to read by converting them to PDF.',
    Icon: ExcelIcon,
    color: 'bg-green-700',
    hoverColor: 'hover:bg-green-800',
    textColor: 'text-green-700',
    category: 'convert-to',
  },
  {
    id: 'edit-pdf',
    title: 'Edit PDF',
    description: 'Add text, images, shapes or freehand annotations to a PDF document.',
    Icon: EditIcon,
    color: 'bg-purple-500',
    hoverColor: 'hover:bg-purple-600',
    textColor: 'text-purple-500',
    isNew: true,
    isPremium: true,
    category: 'edit',
  },
  {
    id: 'pdf-to-jpg',
    title: 'PDF to JPG',
    description: 'Convert each PDF page into a JPG or extract all images contained in a PDF.',
    Icon: PdfToJpgIcon,
    color: 'bg-yellow-500',
    hoverColor: 'hover:bg-yellow-600',
    textColor: 'text-yellow-500',
    category: 'convert-from',
  },
  {
    id: 'jpg-to-pdf',
    title: 'JPG to PDF',
    description: 'Convert JPG images to PDF in seconds. Easily adjust orientation and margins.',
    Icon: JpgToPdfIcon,
    color: 'bg-yellow-500',
    hoverColor: 'hover:bg-yellow-600',
    textColor: 'text-yellow-500',
    category: 'convert-to',
  },
  {
    id: 'sign-pdf',
    title: 'Sign PDF',
    description: 'Sign yourself or request electronic signatures from others.',
    Icon: SignIcon,
    color: 'bg-blue-600',
    hoverColor: 'hover:bg-blue-700',
    textColor: 'text-blue-600',
    isPremium: true,
    category: 'security',
  },
  {
    id: 'watermark-pdf',
    title: 'Watermark',
    description: 'Stamp an image or text over your PDF in seconds. Choose the typography, transparency and position.',
    Icon: WatermarkIcon,
    color: 'bg-purple-500',
    hoverColor: 'hover:bg-purple-600',
    textColor: 'text-purple-500',
    category: 'security',
  },
  {
    id: 'rotate-pdf',
    title: 'Rotate PDF',
    description: 'Rotate your PDFs the way you need them. You can even rotate multiple PDFs at once!',
    Icon: RotateIcon,
    color: 'bg-indigo-500',
    hoverColor: 'hover:bg-indigo-600',
    textColor: 'text-indigo-500',
    category: 'organize',
  },
  {
    id: 'html-to-pdf',
    title: 'HTML to PDF',
    description: 'Convert webpages in HTML to PDF. Copy and paste the URL of the page you want and convert it to PDF with a click.',
    Icon: HtmlToPdfIcon,
    color: 'bg-yellow-600',
    hoverColor: 'hover:bg-yellow-700',
    textColor: 'text-yellow-600',
    category: 'convert-to',
  },
  {
    id: 'unlock-pdf',
    title: 'Unlock PDF',
    description: 'Remove PDF password security, giving you the freedom to use your PDFs as you want.',
    Icon: UnlockIcon,
    color: 'bg-cyan-500',
    hoverColor: 'hover:bg-cyan-600',
    textColor: 'text-cyan-500',
    category: 'security',
  },
  {
    id: 'protect-pdf',
    title: 'Protect PDF',
    description: 'Protect PDF files with a password. Encrypt PDF documents to prevent unauthorized access.',
    Icon: ProtectIcon,
    color: 'bg-blue-800',
    hoverColor: 'hover:bg-blue-900',
    textColor: 'text-blue-800',
    category: 'security',
  },
  {
    id: 'organize-pdf',
    title: 'Organize PDF',
    description: 'Sort pages of your PDF file however you like. Delete PDF pages or add PDF pages to your document at your convenience.',
    Icon: OrganizeIcon,
    color: 'bg-orange-600',
    hoverColor: 'hover:bg-orange-700',
    textColor: 'text-orange-600',
    category: 'organize',
  },
  {
    id: 'pdf-to-pdfa',
    title: 'PDF to PDF/A',
    description: 'Transform your PDF to PDF/A, the ISO-standardized version for long-term archiving.',
    Icon: PdfToPdfAIcon,
    color: 'bg-slate-500',
    hoverColor: 'hover:bg-slate-600',
    textColor: 'text-slate-500',
    isPremium: true,
    category: 'convert-from',
  },
  {
    id: 'repair-pdf',
    title: 'Repair PDF',
    description: 'Repair a damaged PDF and recover data from corrupt PDF. Fix PDF files with our Repair tool.',
    Icon: RepairIcon,
    color: 'bg-lime-600',
    hoverColor: 'hover:bg-lime-700',
    textColor: 'text-lime-600',
    isPremium: true,
    category: 'optimize',
  },
  {
    id: 'page-numbers',
    title: 'Page numbers',
    description: 'Add page numbers into PDFs with ease. Choose your positions, dimensions, typography.',
    Icon: PageNumbersIcon,
    color: 'bg-fuchsia-500',
    hoverColor: 'hover:bg-fuchsia-600',
    textColor: 'text-fuchsia-500',
    category: 'edit',
  },
  {
    id: 'scan-to-pdf',
    title: 'Scan to PDF',
    description: 'Use your phone or computer camera to scan documents and save them as clear, high-quality PDFs.',
    Icon: ScanToPdfIcon,
    color: 'bg-amber-500',
    hoverColor: 'hover:bg-amber-600',
    textColor: 'text-amber-500',
    isNew: true,
    category: 'convert-to',
  },
  {
    id: 'ocr-pdf',
    title: 'OCR PDF',
    description: 'Easily convert scanned PDF into searchable and selectable documents.',
    Icon: OcrPdfIcon,
    color: 'bg-teal-500',
    hoverColor: 'hover:bg-teal-600',
    textColor: 'text-teal-500',
    isPremium: true,
    category: 'edit',
  },
  {
    id: 'compare-pdf',
    title: 'Compare PDF',
    description: 'Show a side-by-side comparison of two PDF files to spot the differences.',
    Icon: ComparePdfIcon,
    color: 'bg-sky-500',
    hoverColor: 'hover:bg-sky-600',
    textColor: 'text-sky-500',
    isPremium: true,
    category: 'edit',
  },
  {
    id: 'redact-pdf',
    title: 'Redact PDF',
    description: 'Redact text and graphics from your PDF to permanently remove sensitive information.',
    Icon: RedactPdfIcon,
    color: 'bg-slate-700',
    hoverColor: 'hover:bg-slate-800',
    textColor: 'text-slate-700',
    isPremium: true,
    category: 'edit',
  },
  {
    id: 'crop-pdf',
    title: 'Crop PDF',
    description: 'Crop margins of PDF files to change the page size or remove unwanted areas.',
    Icon: CropPdfIcon,
    color: 'bg-rose-500',
    hoverColor: 'hover:bg-rose-600',
    textColor: 'text-rose-500',
    isPremium: true,
    category: 'edit',
  },
];

export const blogPosts = [
    {
    slug: 'introducing-chatgpt-integration',
    title: 'Introducing iLovePDFLY + ChatGPT: The custom PDF GPT',
    date: 'Apr 9, 2025',
    excerpt: 'Use ChatGPT as your PDF assistant with iLovePDFLY—no software needed. Just upload, describe, and go.',
    content: `Use ChatGPT as your PDF assistant with iLovePDFLY—no software needed. Just upload, describe, and go. We are excited to announce an innovative integration that combines the power of our PDF tools with the intelligence of ChatGPT. Now you can summarize, translate, or ask questions about your PDF content using natural language. This feature is set to revolutionize how you interact with your documents.`,
    image: 'https://placehold.co/600x400/4c51bf/e0e7ff?text=ChatGPT',
    author: 'Bishal Mishra',
    authorImage: 'https://i.ibb.co/RpStGhqm/IMG-5251-Original.jpg',
    tags: ['AI', 'New Feature', 'Productivity'],
  },
  {
    slug: 'platform-guide-2025',
    title: 'Web, Desktop, or Mobile: Which platform is right for you?',
    date: 'Jan 6, 2025',
    excerpt: `Discover the difference between iLovePDFLY Web, Desktop, and Mobile to find out which is the best option for your document needs.`,
    content: `Discover the difference between iLovePDFLY Web, Desktop, and Mobile to find out which is the best option for your document needs. The Web version offers ultimate convenience with no installation required. The Desktop app provides offline processing and enhanced performance for heavy tasks. The Mobile app is your on-the-go solution for scanning, editing, and signing. This guide breaks down the features of each platform to help you choose the perfect tool for your workflow.`,
    image: 'https://placehold.co/600x400/f3f4f6/1f2937?text=Platforms',
    author: 'Bishal Mishra',
    authorImage: 'https://i.ibb.co/RpStGhqm/IMG-5251-Original.jpg',
    tags: ['Guide', 'Productivity'],
  },
  {
    slug: 'how-to-edit-pdf-text-online',
    title: 'How to edit text directly in your PDF files online',
    date: 'May 30, 2024',
    excerpt: `Our PDF editor lets you edit PDF text directly, automatically detecting and matching the text style, and offering customizable formatting.`,
    content: `Our PDF editor lets you edit PDF text directly, automatically detecting and matching the text style, and offering customizable formatting. Need to fix a typo or update a date in a PDF? Our advanced PDF editor makes it possible. This post walks you through the process, showing you how to select and edit text just like you would in a word processor, saving you the hassle of converting the file back and forth.`,
    image: 'https://placehold.co/600x400/fef08a/854d0e?text=Edit+Text',
    author: 'Bishal Mishra',
    authorImage: 'https://i.ibb.co/RpStGhqm/IMG-5251-Original.jpg',
    tags: ['PDF Tools', 'How-To', 'Editing'],
  },
  {
    slug: 'smart-ocr-tips',
    title: 'Smart OCR tips: how to get the most out of your scanned documents',
    date: 'May 30, 2024',
    excerpt: `Boost your OCR results with smart scanning techniques. Learn how resolution, contrast, and language support affect text recognition accuracy.`,
    content: `Boost your OCR results with smart scanning techniques. Learn how resolution, contrast, and language support affect text recognition accuracy. Optical Character Recognition (OCR) is a powerful technology, but its accuracy depends on the quality of the source image. This guide provides tips on how to scan your documents to achieve the best possible OCR results, ensuring your text is searchable and selectable with high fidelity.`,
    image: 'https://placehold.co/600x400/fecaca/991b1b?text=OCR+Tips',
    author: 'Bishal Mishra',
    authorImage: 'https://i.ibb.co/RpStGhqm/IMG-5251-Original.jpg',
    tags: ['OCR', 'Productivity', 'Guide'],
  },
  {
    slug: 'are-digital-signatures-legally-binding',
    title: 'Are digital signatures legally binding?',
    date: 'Mar 2, 2024',
    excerpt: `Digital signatures are a top choice for cross-border business transactions. But are they legally binding? Here's how to check.`,
    content: `Digital signatures are a top choice for cross-border business transactions. But are they legally binding? Here's how to check. The short answer is yes, in many parts of the world, digital signatures carry the same legal weight as a handwritten signature. Laws like the ESIGN Act in the United States and eIDAS in the European Union provide a legal framework for their use. However, the level of validity can depend on the type of digital signature used and the jurisdiction. Our "Sign PDF" tool provides a secure and verifiable way to sign documents, complete with timestamps and audit trails, which strengthens their legal standing. For transactions requiring the highest level of assurance, it's always a good idea to consult with a legal professional to ensure compliance with local regulations.`,
    image: 'https://placehold.co/600x400/cffafe/0e7490?text=e-Signatures',
    author: 'Bishal Mishra',
    authorImage: 'https://i.ibb.co/RpStGhqm/IMG-5251-Original.jpg',
    tags: ['Security', 'E-Sign', 'Legal'],
  },
  {
    slug: 'how-to-add-a-password-to-a-pdf',
    title: 'How to add a password to a PDF',
    date: 'Mar 7, 2023',
    excerpt: `Find out how to keep your sensitive data secure by adding a password to the original PDF document.`,
    content: `Find out how to keep your sensitive data secure by adding a password to the original PDF document. In an age where data privacy is paramount, protecting your documents is more important than ever. Our "Protect PDF" tool offers a simple yet robust solution to encrypt your files with a password. This process ensures that only authorized individuals can access the content. To get started, simply upload your PDF, enter a strong password, and let our tool handle the rest. The encryption is done securely on our servers, and your files are automatically deleted after a few hours to guarantee your privacy. This feature is perfect for sharing confidential reports, personal information, or any document that needs an extra layer of security.`,
    image: 'https://placehold.co/600x400/dbeafe/1e40af?text=Password+PDF',
    author: 'Bishal Mishra',
    authorImage: 'https://i.ibb.co/RpStGhqm/IMG-5251-Original.jpg',
    tags: ['Security', 'How-To', 'PDF Tools'],
  },
  {
    slug: 'you-can-now-edit-images-in-ilovepdf',
    title: 'You can now edit images in iLovePDFLY',
    date: 'Mar 7, 2023',
    excerpt: `We also love...images! The latest iLovePDFLY Mobile App includes new tools to edit images on the go. Here's everything you need to know.`,
    content: `We also love...images! The latest iLovePDFLY Mobile App includes new tools to edit images on the go. Here's everything you need to know. The world of digital documents is constantly evolving, and so are we. We're thrilled to announce a major update to our mobile application that brings powerful image editing capabilities right to your fingertips. Whether you need to crop, rotate, or annotate an image before adding it to your PDF, our new tools make it seamless and intuitive. This update is designed to streamline your workflow, eliminating the need to switch between multiple applications for your document and image editing needs. We believe this will be a game-changer for students, professionals, and anyone who works with visual content on a regular basis. Download the latest version today and explore the new possibilities!`,
    image: 'https://placehold.co/600x400/e0e7ff/4338ca?text=Edit+Images',
    author: 'Bishal Mishra',
    authorImage: 'https://i.ibb.co/RpStGhqm/IMG-5251-Original.jpg',
    tags: ['Update', 'Mobile', 'Editing'],
  },
  {
    slug: 'how-to-convert-html-websites-into-pdf-files',
    title: 'How to convert HTML websites into PDF files',
    date: 'Jul 5, 2022',
    excerpt: `Have you tried to download a webpage before, only to be left with a faulty file? Use this tool to accurately convert web pages into PDF documents.`,
    content: `Have you tried to download a webpage before, only to be left with a faulty file that's cut the most important graph in half? Use this online tool to accurately convert web pages into PDF documents. Our HTML to PDF converter is designed to capture the entire content of a webpage, including text, images, and layout, and preserve it in a high-quality PDF. This is incredibly useful for archiving articles, saving online receipts, or creating offline reading material. Simply paste the URL of the webpage you want to convert, and our tool will generate a perfectly formatted PDF in seconds. Say goodbye to awkward screenshots and incomplete printouts.`,
    image: 'https://placehold.co/600x400/fef9c3/854d0e?text=HTML+to+PDF',
    author: 'Bishal Mishra',
    authorImage: 'https://i.ibb.co/RpStGhqm/IMG-5251-Original.jpg',
    tags: ['How-To', 'PDF Tools', 'Conversion'],
  },
];